### ISSUE TITLE
About the pre-trained weights

### ISSUE THREAD

**Issue by zzzyzh** [CAMMA-public/SelfPose3d#10]
Thank you for providing the backbone weights. However, when I attempting to run inference directly, I noticed that a critical pre-trained model weight file, `model_best.pth.tar`, seems to be missing, which prevents me from proceeding with the inference.

Could you kindly provide the complete pre-trained weight file `model_best.pth.tar`? This would be tremendously helpful for running the model and advancing my research.

**Comment by keqizero** [comment]
The trained model is already uploaded and named as cam5_posenet.pth.tar. Please check the README file. You can rename it as you wish.
