### ISSUE TITLE
SMPL Prediction

### ISSUE THREAD

**Issue by SWWdz** [CAMMA-public/SelfPose3d#11]
Thanks for your work. In your paper, you have shown the CMU dataset's SMPL mesh predictions. I am interested  in this problem. Can you tell me how to use your network to predict the SMPL mesh in detail.

**Comment by keqizero** [comment]
Hi, we use [smplify-x](https://github.com/vchoutas/smplify-x) to predict the SMPL mesh.

**Comment by SWWdz** [comment]
Can you share the code how to use smplify-x to predict the SMPL mesh? 
Thanks for your help.
