### ISSUE TITLE
README not reproducable: CMU Panoptic dataset image extraction missing

### ISSUE THREAD

**Issue by LadnerJonas** [CAMMA-public/SelfPose3d#3]
Recently, I received access to a cuda-machine to test this project. I am now trying to continue reproducing the README. Afterward, we want to run SelfPose3d on our videos and data.

To my current understanding, SelfPose3d requires to extract images / hdPose3d / calibration from the video data set. This can easily be done using the panoptic-toolbox script.
e.g.
`./panoptic-toolbox/scripts/extractAll.sh SelfPose3d/data/panoptic-toolbox/data/160224_haggling1/`

After that, all necessary folders and files are generated.

Can you please add something similar to the project README file?

**Comment by LadnerJonas** [comment]
Also, please note that the 16060224_haggling1 is now called 160224_haggling1

**Comment by keqizero** [comment]
Hi, 

Yes, we extracted the images by following the scripts written in the Panoptic repository. Thank you, and I will update the README file.
