### ISSUE TITLE
About the preparation of the data

### ISSUE THREAD

**Issue by zzzyzh** [CAMMA-public/SelfPose3d#9]
Hi,
How can I use panoptic-toolbox to get a dataset that is compatible with the one you are using? Can you give me a command to download it?

**Comment by keqizero** [comment]
Hi, 

As mentioned in the README, we used the scripts provided by [Panoptic-Toolbox](https://github.com/CMU-Perceptual-Computing-Lab/panoptic-toolbox/tree/master/scripts) to download the data. More specifically, please refer to [scripts/getData.sh](https://github.com/CMU-Perceptual-Computing-Lab/panoptic-toolbox/blob/master/scripts/getData.sh) and [scripts/hdImgsExtractor.sh](https://github.com/CMU-Perceptual-Computing-Lab/panoptic-toolbox/blob/master/scripts/hdImgsExtractor.sh).

**Comment by zzzyzh** [comment]
Thank you for your patience in replying

How do I get the sequenceName I need? Also, when the paper says “five HD camera images (3, 6, 12, 13, 23) ” does it mean numHDViews?

Looking forward to your reply!
